services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  task-service:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
